name: devnet-bundle-snapshot-action
description: Devnet Bundle Snapshot Action

inputs:
  nexus_id:
    description: "Nexus ID"
    required: true
  nexus_user:
    description: "Nexus User"
    required: true
  nexus_user_pw:
    description: "Nexus User Password"
    required: true
  nexus_url:
    description: "Nexus Url"
    required: true
  nexus_url_release:
    description: "Nexus Url Release"
    required: true
  nexus_url_snapshots:
    description: "Nexus Url Snapshots"
    required: true
  release_token:
    description: "Release Token"
    required: true
  demo_user:
    description: "Demo User"
    required: true
  demo_user_pw:
    description: "Demo User PW"
    required: true
  demo_url:
    description: "Demo URL"
    required: true

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v3
    - id: cache-node
      name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          '**/node'
          '**/node_modules'
          ~/.m2/repository
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
    - id: setup
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - id: create_settings_xml
      name: Create settings.xml
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        repositories: >
          [
            {
              "id": "central",
              "url": "http://central",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "central",
              "url": "http://central",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "${{ inputs.nexus_id }}",
              "username": "${{ inputs.nexus_user }}",
              "password": "${{ inputs.nexus_user_pw }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "${{ inputs.nexus_id }}",
              "mirrorOf": "central",
              "url": "${{ inputs.nexus_url }}"
            }
          ]
    - id: project_version
      name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      shell: bash
    - id: project_artifact_id
      name: Extract Maven project artifactId
      run: echo ::set-output name=artifactId::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
      shell: bash
    - id: tests
      name: Run tests
      run: mvn prepare-package -B -ntp -Prun-js-tests,include-mapapps-deps
      shell: bash
    - id: nexus_deployment
      name: Publish to Nexus
      run: mvn clean deploy -B -ntp -Pcompress -Dmaven.test.skip.exec=true -Ddist.releases.id=${{ inputs.nexus_id }} -Ddist.releases.url=${{ inputs.nexus_url_release }} -Ddist.snapshots.id=${{ inputs.nexus_id }} -Ddist.snapshots.url=${{ inputs.nexus_url_snapshots }}
      shell: bash
    - id: release
      name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/${{ steps.project_artifact_id.outputs.artifactId }}-bundle.zip,target/${{ steps.project_artifact_id.outputs.artifactId }}-sample-app.zip"
        preRelease: true
        bodyFile: "RELEASE.md"
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ steps.project_version.outputs.version }}
        token: ${{ inputs.release_token }}
    - id: upload_demo
      name: Upload to demo
      run: mvn package -Pcompress,upload -Dmapapps.remote.base=${{ inputs.demo_url }} -Ddemo.user=${{ inputs.demo_user }} -Ddemo.user.pw=${{ inputs.demo_user_pw }}
      shell: bash
